# Generated by Django 6.0.4 on 2026-04-20 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.academicclass'),
        ),
    ]
