# Generated by Django 6.0.4 on 2026-04-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_parent_email_assignmentsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
